# -*- coding: utf-8 -*-
"""grade_calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoShe0fViuiW8D22J5lMtCLGzwsOIJIJ
"""

# Student Grade Calculator
# Week 2 Final Project

def calculate_grade(marks):
    if marks >= 90:
        return "A", "Excellent work! 🌟"
    elif marks >= 80:
        return "B", "Very Good! Keep it up! 👍"
    elif marks >= 70:
        return "C", "Good job! You can do even better 😊"
    elif marks >= 60:
        return "D", "You passed, but practice more 💪"
    else:
        return "F", "Don't worry, keep trying! 🌈"


# Main Program
student_name = input("Enter student name: ")

# Input validation using while loop
while True:
    marks = int(input("Enter marks (0-100): "))
    if 0 <= marks <= 100:
        break
    else:
        print("❌ Invalid marks! Please enter between 0 and 100.")

grade, message = calculate_grade(marks)

print("\n📊 RESULT")
print("Student Name:", student_name)
print("Marks:", marks)
print("Grade:", grade)
print("Message:", message)